name: Deploy React App to AWS EC2 and run Docker container

on:
  push:
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_REPOSITORY}}:${{ vars.DOCKERHUB_TAG }}
        
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
         host: ${{ vars.HOSTNAME }}
         username: ${{ vars.USER_NAME }}
         key: ${{ secrets.SSH_AWS_FAMBUDGET }}
         port: ${{ vars.SSH_PORT }}
         script: | 
             docker login --username=${{ secrets.DOCKER_USER}} --password=${{ secrets.DOCKER_PASSWORD }}
             sudo docker stop ${{ vars.CONTAINER_NAME }}
             sudo docker rm ${{ vars.CONTAINER_NAME }}
             sudo docker rmi {{ secrets.DOCKER_HUB_REPOSITORY }}:${{ vars.DOCKERHUB_TAG }}
             sudo docker run -d --name '${{ vars.CONTAINER_NAME }}' --network=${{ vars.CONTAINER_NETWORK }} ${{ secrets.DOCKER_HUB_REPOSITORY}}:${{ vars.DOCKERHUB_TAG }}
